#server:
#  port: 9000
#
##服务名称
#spring:
#  application:
#    name: video-service
#  #添加zipkin
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    discovery-client-enabled: false
#  #添加sleuth采样百分比  10个请求记录1次为0.1
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比为100%
#
#  cloud:
#    #    配置nacos
#    nacos:
#      discovery:
#        server-addr: 61.135.32.130:58848
#          #配置sentinel
#    sentinel:
#      transport:
#        dashboard: localhost:59999    #控制台ip端口
#        port: 60002     #微服务和控制台通讯的端口
#
##    数据库连接
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://61.135.32.130:23305/cloud_video?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456
#
## 控制台输出sql、下划线转驼峰
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true