#server:
#  port: 8888
#
##服务名称
#spring:
#  application:
#    name: api-gateway
#  #添加zipkin  持久化操作：java -jar zipkin-server-2.12.9-exec.jar --STORAGE_TYPE=mysql --MYSQL_HOST=127.0.0.1 --MYSQL_TCP_PORT=3306 --MYSQL_DB=zipkin_log --MYSQL_USER=root --MYSQL_PASS=net.xdclass.net
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    discovery-client-enabled: false
#  #添加sleuth采样百分比  10个请求记录1次为0.1
#  sleuth:
#    sampler:
#      probability: 1.0 #采样百分比为100%
#  cloud:
#    #    配置nacos
#    nacos:
#      discovery:
#        server-addr: 61.135.32.130:58848
#    gateway:
#      routes:  #数组形式
#        - id: video-order-service   #路由唯一标识和路径无关
#          #uri: http://127.0.0.1:8000  #想要转发到的地址
#          uri: lb://video-order-service   #从nacos进行拉取对应的服务名称，lb是实现负载均衡
#          order: 1  #优先级，数字越小优先级越高
#          predicates:  #断言 配置哪个路径才转发,网关收到路径匹配这一条然后拼接uri，再去掉前缀去请求服务http://localhost:8888/aa/api/v1/video_order/list
#            - Path=/aa/**  #满足该路径进行转发，如果有多个则都需要满足才行 RoutePredicateFactory
##            - Before=2020-11-27T01:01:01.000+08:00    #指定在某个时间以前可以访问
##            - Query=source                            #任何请求中必须带source参数：http://localhost:8888/aa/api/v1/video_order/list?source=wechat
##            - Host=
##            - Method=
##            - Header=
##            - Cookie=
#          filters:  #局部过滤器，请求在传递过程中通过过滤器修改
#            - StripPrefix=1  #去掉第一层前缀
#      discovery:
#        locator:
#          enabled: true    #开启网关拉取nacos的服务
#
#    #        - id: video-service   #路由唯一标识和路径无关
##            uri: http://localhost:8000  #想要转发到的地址
##            order: 1  #优先级，数字越小优先级越高
##            predicates: #断言 配置那个路径才转发
##              - Path=/order-service/**
##            filters: #过滤器，请求在传递过程中通过过滤器修改
##              - StripPrefix=1  #去掉第一层前缀
#
#    #配置sentinel
##    sentinel:
##      transport:
##        dashboard: localhost:59999    #控制台ip端口
##        port: 60003     #微服务和控制台通讯的端口
#
#
#  #    数据库连接
##  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://61.135.32.130:23305/cloud_video_order?useUnicode=true&characterEncoding=utf8&useSSL=false
##    username: root
##    password: 123456
#
## 控制台输出sql、下划线转驼峰
##mybatis:
##  configuration:
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
##    map-underscore-to-camel-case: true
#
##配置ribbon负载均衡，和openfeign也有关，openfeign底层就是ribbon
##常用 默认 的和 WeightedResponseTimeRule
##video-service:
##  ribbon:
##    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule   #该策略是随机请求video-service的某个服务
#
#
##开启feign支持sentinel
##feign:
##  sentinel:
##    enabled: true
